name: project_ppb
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.19.0
  carousel_slider: ^4.0.0  
  firebase_core: ^3.1.0
  # firebase_auth: ^5.1.0
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  webview_flutter: ^4.8.0
  horizontal_week_calendar: ^0.0.17

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  auto_size_text: ^3.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/doctor1.png
    - assets/doctor2.png
    - assets/doctor3.png
    - assets/doctor4.png
    - assets/doctor5.png
    - assets/doctor6.png
    - assets/customer1.png
    - assets/prescription.png
    - assets/article1.png
    - assets/article2.png
    - assets/article3.png
    - assets/profile_image.png
    - assets/logo.png